base_config: &base_config
  STRIPE_SECRET_KEY: <YOUR KEY>
  STRIPE_PUBLISHABLE_KEY: <YOUR PUB KEY>

development: &development
  <<: *base_config

test: &test
  <<: *base_config

production: &production
  STRIPE_SECRET_KEY: <YOUR KEY>
  STRIPE_PUBLISHABLE_KEY: <YOUR PUB KEY>
